server:
  port: 8081

spring:
  profiles:
    active: dev

  jackson: # jackson json 格式化工具配置
    serialization:
      indent_output: true #格式化输出
      fail_on_empty_beans: false #忽略无法转换的对象
    defaultPropertyInclusion: NON_EMPTY #设置空如何序列化
    deserialization:
      fail_on_unknown_properties: false #允许对象忽略json中不存在的属性
    parser:
      allow_unquoted_control_chars: true #允许出现特殊字符和转义符
      allow_single_quotes: true #允许出现单引号

  zipkin:
    enabled: true # 启用 Zipkin 链路追踪
    locator:
      discovery:
        enabled: true  # 通过注册中心发现服务 ID
    compression:
      enabled: true # 压缩数据
    sender: # 使用 rabbitmq 发送数据
      type: rabbit
    rabbitmq:
      topic: zipkin

  sleuth:
    enabled: true
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true

feign:  #feign的配置
  httpclient:
    connection-timeout: 5000  #连接超时配置
    enabled: true
  compression: # 请求响应数据压缩配置
    request:
      enabled: true
      min-request-size: 1024 # 请求数据压缩阈值
    response:
      enabled: true

eureka: # 注册中心配置
  instance:
    hostname: register-center
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8860/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refres
  server:
    servlet:
      context-path: /