server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  profiles:
    active: dev

  jackson: # jackson json 格式化工具配置
    serialization:
      indent_output: true #格式化输出
      fail_on_empty_beans: false #忽略无法转换的对象
    defaultPropertyInclusion: NON_EMPTY #设置空如何序列化
    deserialization:
      fail_on_unknown_properties: false #允许对象忽略json中不存在的属性
    parser:
      allow_unquoted_control_chars: true #允许出现特殊字符和转义符
      allow_single_quotes: true #允许出现单引号

eureka:
  instance:
    hostname: register-center
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8860/eureka/

user:
  name: Smilly
  identity: 21011220040804555X
  age: 26
  sex: male