server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  profiles:
    active: dev

eureka:
  instance:
    hostname: register-center
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@register-server:8860/eureka/

user:
  name: Smilly
  age: 26
  sex: male