server:
  port: 8850

spring:
  profiles:
    active: dev

  security:
    user:
      name: ${ZIPKIN_SERVER_USERNAME:zipkin}
      password: ${ZIPKIN_SERVER_PASSWORD:zipkin}

# 注册服务到注册中心
eureka:
  instance:
    hostname: register-center
    prefer-ip-address: true
    metadata-map:
      user.name: ${srping.security.user.name}
      user.password: ${srping.security.user.password}
  client:
    service-url:
      defaultZone: http://${REGISTER_CENTER_USERNAME:register}:${REGISTER_CENTER_PASSWORD:register}@localhost:8860/eureka/

zipkin:
  storage: # es 配置
    strict-trace-id: true
    search-enabled: true
    type: elasticsearch
    elasticsearch:
      hosts: http://localhost:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1
  collector: # rabbitmq collector 配置
    rabbitmq:
      enabled: true
      addresses: localhost:5672
      username: guest
      password: guest
      queue: zipkin

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: '*'