server:
  port: 8888

spring:
  application:
    name: ${project.artifactId}
    version: ${project.version}

  profiles:
    active: ${profile.active}

  cloud:
    config:
      server:
        git: # 配置中心文件位置
          uri: ${config.server.rsc.url}
          search-paths: ${config.server.rsc.path} # 文件基路径
          username: ${config.server.rsc.username}
          password: ${config.server.rsc.password}
          force-pull: true #强制拉取
          delete-untracked-branches: true #删除无关分支

  rabbitmq: # 消息总线配置
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

eureka: # 向注册中心注册
  instance:
    hostname: ${registry.server.name}
    prefer-ip-address: true
  client:
    fetch-registry: true # 从eureka服务器获取eureka注册表信息
    service-url:
      defaultZone: http://${registry.server.host}:${registry.server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'