server:
  port: 8888

spring:
  profiles:
    active: dev

  cloud:
    config:
      server:
        git: # 配置中心文件位置
          uri: https://github.com/20087843/spring-cloud-demo
          search-paths: config-repo # 文件基路径
          force-pull: true #强制拉取
          delete-untracked-branches: true #删除无关分支

  rabbitmq: # 消息总线配置
    host: localhost
    port: 5672
    username: guest
    password: guest

# 向注册中心注册
eureka:
  instance:
    hostname: register-center
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8860/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'