server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git: # 配置中心文件位置
          uri: https://github.com/20087843/spring-cloud-demo
          search-paths: config-repo #
          force-pull: true #强制拉取
          delete-untracked-branches: true #删除无关分支

  active: dev # 开发模式

  rabbitmq: # 消息总线配置
    host: localhost
    port: 5672
    username: guest
    password: guest

# 向注册中心注册
eureka:
  instance:
    hostname: register-center
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@register-server:8860/eureka/

management:
  server:
    ssl:
      enabled: false
